var nombre = prompt ('Ingrese el nombre del alumno')
var nota1= prompt('Ingresar nota de Historia')
var nota2= prompt('Ingresar nota de Ingles')
var nota3= prompt('Ingresar nota de Matematica')
document.write("<h3>"+'Nombre de alumno:'+" "  +  nombre +"</h3>" +"<br>")
document.write('Nota de historia:'+" " +nota1 + "<br>")
document.write('Nota de Ingles:'+" " +nota2 + "<br>")
document.write('Nota de Matematica:'+" " +nota3 + "<br>")
var promedio = (parseFloat(nota1)+parseFloat(nota2)+parseFloat(nota3))/3
document.write('Su promedio es: '+" "+parseFloat(promedio) + "<br>")
console.log('Nombre: '+ nombre)
console.log('Nota de historia:' +nota1)
console.log('Nota de Ingles:' +nota2)
console.log('Nota de Matematica:' +nota3)
console.log('Su promedio es: '+promedio)
